name: byhagene
favicon: null
layout_spectrum: 0.47367590898647904
typography_spectrum: 0.48706982424482703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1894482453353703
  lightness: 0.7339460698422045
  saturation: 0.20129749574698508
  rhythmicContrast: 0.44890588195994496
purpose: []
