name: byhagene
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26232a'
    - '#cfab91'
    - '#ffffff'
    - '#6a3c25'
    - '#6a6751'
  brandStrength: 0.125
  lightness: 0.7339460698422045
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
